# Etapa 1: Compilación, con pequeños cambios
FROM maven:3.8.8-eclipse-temurin-17 AS build
WORKDIR /app
COPY ventas/pom.xml .
RUN mvn dependency:go-offline
COPY ventas/src ./src
RUN mvn clean package -DskipTests

# Etapa 2: Ejecución app, con puerto 8080
FROM eclipse-temurin:17-jre
WORKDIR /app
RUN groupadd -r appgroup && useradd -r -g appgroup appuser
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
USER appuser
ENTRYPOINT ["java", "-jar", "app.jar"]